#!/bin/bash

set -e

prepare_build_env() {
  rpmdev-setuptree
  copy_spec_and_tar_with_binaries
}

copy_spec_and_tar_with_binaries() {
  if [ "${os}_${os_codename}" == "fedora_thirtyfive" ]; then
    cp /src/fedora/kasmvncserver.spec ~/rpmbuild/SPECS/
  else
    cp /src/centos/kasmvncserver.spec ~/rpmbuild/SPECS/
  fi
  cp /src/builder/build/kasmvnc.${os}_${os_codename}.tar.gz \
    ~/rpmbuild/SOURCES/
}

copy_rpm_to_build_dir() {
  cd /src/builder && \
    mkdir -p "$os_dir" && cp ~/rpmbuild/RPMS/*/*.rpm ${os_dir}
}

cd "$(dirname "$0")/.."

os=$(lsb_release -is | tr '[:upper:]' '[:lower:]')
os_codename=$(lsb_release -cs | tr '[:upper:]' '[:lower:]')
os_dir="build/${os}_${os_codename}"

prepare_build_env
rpmbuild -ba ~/rpmbuild/SPECS/kasmvncserver.spec
copy_rpm_to_build_dir
rpmlint "$os_dir"/*.rpm || true
